config/routes.rb
Rails.application.routes.draw do
  resources :avatars
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  resources :tasks
  resources :starred_tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  patch "/users/edit/avatar/:id", to: "application#change_avatar"
  get "/tasks/date/:date", to: "tasks#get_tasks_by_date", as: "tasks_by_date"
  patch "/tasks/:id/task_complete", to: "tasks#mark_complete",  as: "mark_complete"
  patch "/tasks/:id/task_uncomplete", to: "tasks#mark_uncomplete" , as: "mark_uncomplete"
  get "/tasks/:id", to: "tasks#show", as: "show_task"


  # collab
  get "/collab", to: "tasks#collab_requests", as: "collab_request"
  patch "/collab/accept/:task_id", to: "collaborators#accept_request", as: "accept_request"
  patch "/collab/reject/:task_id", to: "collaborators#reject_request", as: "reject_request"
  patch "/collab/complete/:task_id", to: "collaborators#mark_complete", as: "collab_mark_complete"
  put "/collab/complete/:task_id", to: "collaborators#mark_uncomplete", as: "collab_mark_incomplete"

  # collab email API
  get "/collab/emails/:email_string", to: "collaborators#get_emails"


  # starred tasks
  get "/starred_tasks/", to: "starred_tasks#index"
  post "/starred_tasks/:id", to: "starred_tasks#add", as:"add_to_starred"
  delete "/starred_tasks/:id", to: "starred_tasks#destroy", as:"remove_starred"

end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: { greater_than: :start_date }
  validates_length_of :title, minimum: 8, maximum: 20

  belongs_to :user
  has_many :starred_tasks, dependent: :destroy
  has_many :collaborators, dependent: :destroy

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ edit update destroy mark_complete mark_uncomplete ]
  before_action :get_user, only: %i[ new create index]
  before_action :collab_data, only: %i[index collab_requests get_tasks_by_date]
  before_action :collab_tasks, only: %i[index collab_requests get_tasks_by_date]
  before_action :before_show, only: %i[show]
  before_action :get_tasks, only: %i[collab_requests]
  before_action :authenticate_user!
  
  # GET /tasks or /tasks.json
  def index
    if (params[:search])
      @tasks = current_user.tasks.where(["title LIKE ?","%#{params[:search]}%"])
    else
      @tasks = current_user.tasks.where(start_date: Date.parse("#{Time.now}")..Date.parse("#{Time.now}").next).order("start_date DESC");
    end
  end

  # collaborators
  # GET /tasks/collabrequests
  def collab_requests
    @collab_requests = Task.joins(:user, :collaborators).joins("inner join avatars on avatars.id = users.avatar_id").select("collaborators.task_id, tasks.title, tasks.end_date, users.full_name, users.email, avatars.avatar_url").where("collaborators.user_id = #{current_user.id} and collaborators.is_accepted != true").where("tasks.end_date > ?", Time.now.utc).order("collaborators.created_at DESC")
    render :index, notice: "collab requests updated"
  end



  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @collaborators = Collaborator.joins(:task, :user).select("collaborators.*, users.email").where(task_id: @task.id)
  end

  # POST /tasks or /tasks.json
  def create
    # puts params["collab"]["email"]
    @task = current_user.tasks.create(task_params)
    @collaborators = []
      if @task.save
        # add collab
        add_or_remove_collaborator(params["collab"]["emails"], @task.id, "ADD")
        redirect_to tasks_by_date_url(Date.parse(@task.start_date.strftime("%Y-%m-%d"))), notice: "Task was successfully created"
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @collaborators = Collaborator.joins(:task, :user).select("collaborators.*, users.email").where(task_id: @task.id)

    if @task.update(task_params)
      if params["collab"]["emails"]
        add_or_remove_collaborator(params["collab"]["emails"], @task.id, "ADD")
      end

      if params["collab"]["remove_emails"]
        add_or_remove_collaborator(params["collab"]["remove_emails"], @task.id, "REMOVE")
      end

      redirect_to tasks_by_date_url(Date.parse(@task.start_date.strftime("%Y-%m-%d"))), notice: "Task was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    if @task
      @task.destroy
      redirect_to tasks_by_date_url(Date.parse(@task.start_date.strftime("%Y-%m-%d"))), notice: "Task deleted"
    else
      redirect_to "/tasks" , notice: "Task could not be deleted"
    end
  end

  # get/show task/1
  def show
    # @collaborators = Collaborator.find_by(task_id: params[:id], user_id: current_user.id)

    @task = Task.find(params[:id])
    @collaborators = @task.collaborators.joins(:user).joins("left join avatars on avatars.id = users.avatar_id").select("collaborators.*, users.email, avatars.avatar_url")

    render :show
  end

  # PUT/PATCH /tasks/1
  def mark_complete
    if @task.update({:is_completed => true})
      redirect_to tasks_by_date_url(Date.parse(@task.start_date.strftime("%Y-%m-%d"))), notice: "Task marked completed"
    else
      render :index, status: :unprocessable_entity
    end
  end

  # PUT/PATCH /tasks/1
  def mark_uncomplete
    if @task.update({:is_completed => false})
      redirect_to tasks_by_date_url(Date.parse(@task.start_date.strftime("%Y-%m-%d"))), notice: "Task marked uncompleted"
    else
      render :index, status: :unprocessable_entity
    end
  end


  # GET /tasks/date/2022-10-19
  def get_tasks_by_date
  if params[:date]
    next_day_date = Date.parse(Date.parse(params[:date]).strftime("%Y-%m-%d")).next;
    @tasks = current_user.tasks.where(start_date: (params[:date])..("#{next_day_date}")).order("start_date DESC");
    @date = params[:date]
    render :index, notice: "tasks updated"
  else
    redirect_to :index, notice: "specify date"
  end
  end


  #  add collab
  def add_or_remove_collaborator(emails, task, action)
    if emails.length() > 0
      emails.each do |email|
        if current_user.email != email.downcase
          user = User.select("users.id").find_by(email: email.downcase);
          if user && action == "ADD"
            is_in_collab = Collaborator.find_by({task_id: task, user_id: user.id})
            if is_in_collab == nil
              Collaborator.create({task_id: task, user_id: user.id, is_accepted: false, is_completed: false});
            end
          elsif user && action == "REMOVE"
            Collaborator.delete_by({task_id: task, user_id: user.id});
          end
        end
      end
    end
  end


  private
    # # Use callbacks to share common setup or constraints between actions.

    # get task
    def get_tasks
      @tasks = current_user.tasks.where(start_date: Date.parse("#{Time.now}")..Date.parse("#{Time.now}").next).order("start_date DESC");
    end

    # set task
    def set_task
      begin
        # do something dodgy
        @task = current_user.tasks.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        # handle not found error
        redirect_to "/tasks", alert: "Only Task creator has access"
      end
    end

    # get user
    def get_user
      @user = User.find(current_user.id)
    end

    # send collab data
    def collab_data
      if current_user
        @collab_data = current_user.tasks.joins("right join collaborators on collaborators.task_id = tasks.id inner join users on users.id = collaborators.user_id left join avatars on avatars.id = users.avatar_id").select("tasks.id as taskId, collaborators.*, users.email, avatars.avatar_url").where("start_date > ?", params[:date] ? Time.parse("#{params[:date]}") : Date.new).where("collaborators.is_accepted = true")
      end
    end

    # get accepted collab tasks
    def collab_tasks
      if params[:date]
        next_day_date = Date.parse(Date.parse(params[:date]).strftime("%Y-%m-%d")).next;
        @collab_tasks = Task.where(start_date: (params[:date])..("#{next_day_date}")).joins(:collaborators).select("tasks.*, collaborators.is_completed as collab_is_complete").where("collaborators.user_id = #{current_user.id} and collaborators.is_accepted = true").order("start_date DESC");
      else
        @collab_tasks = Task.where(start_date: Date.parse("#{Time.now}")..Date.parse("#{Time.now}").next).joins(:collaborators).select("tasks.*, collaborators.is_completed as collab_is_complete").where("collaborators.user_id = #{current_user.id} and collaborators.is_accepted = true").order("start_date DESC");
      end
      @collab_tasks_data = @collab_tasks.joins("right join collaborators on collaborators.task_id = tasks.id inner join users on users.id = tasks.user_id inner join avatars on avatars.id = users.avatar_id").select("tasks.id as taskId, collaborators.*, users.email, avatars.avatar_url").where("start_date > ?", params[:date] ? Time.parse("#{params[:date]}") : Date.new).where("collaborators.is_accepted = true")
    end

    # before_show
    def before_show
        collaborator = Collaborator.find_by(task_id: params[:id], user_id: current_user.id)
        task = current_user.tasks.where(id: params[:id], user_id: current_user.id)

        if  task.empty? && collaborator.nil?
          redirect_to "/tasks", alert: "Only Task creator has access"
        end
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:id, :title, :description, :start_date, :end_date, :is_completed, :search, :date, emails: [], existing_emails: [], remove_emails: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_collab_request.html.erb
<div class="bg-c p-2 rounded-lg flex f-c mb-2">
  <div class="flex f-center mb-2">
    <%= image_tag collab.avatar_url, class: "avatar avatar-md mr-1" %>
    <div class="flex f-c">
    <h4 class="capitize"><%= collab.full_name %></h4>
    <p class="text-sm"><%= collab.email %></p>
    </div>
  </div>
  <p class="text-sm mb-1"><%= collab.full_name %> has requested you to do collaboration with a task.</p>
  <h3 class="mb-2"><%= collab.title %></h3>
    <p class="text-sm">Accept before</p>
  <div class="flex f-center mb-3">
    <span class="material-symbols-outlined mr-1 text-md">
      calendar_month
    </span>
    <p class="text-bl text-sm"><%= collab.end_date.strftime("%^b %d, %Y %I:%M %p") %></p>
  </div>

  <div class="flex jc-sb w-100">
    <%= link_to "Accept",accept_request_path({task_id: collab.task_id}), method: :patch, data: {"confirm": :"Are you sure?"}, class: "btn btn-success w-100 mr-1" %>
    <%= link_to "Reject",reject_request_path({task_id: collab.task_id}), method: :patch, data: {"confirm": :"Are you sure?"},class: "btn btn-danger w-100 ml-1" %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field">
    <%= form.label :title, style: "display: block", class: "mb-2" %>
    <%= form.text_field :title , placeholder: "Title", class: "input-slate" %>
  </div>
  <div class="input-field">
    <%= form.label :description, style: "display: block", class: "mb-2" %>
    <%= form.text_area :description , placeholder: "Write Description...", class: "input-slate", rows: "10" %>
  </div>
  <h2 class="hd-md mt-4 ">Pick Date</h2>
  <div class="flex f-space-between mb-3">
    <div class="input-field date-pickers">
      <%= form.label :start_date, style: "display: block", class: "text-b " %>
      <% if task.start_date %>
        <script></script>
        <%= form.text_field :start_date , class: "start-date flatpickr-input", placeholder: "Select date..", value: task.start_date.strftime("%^b %-d, %Y %I:%M %p"),"data-id": task.start_date.strftime("%Y-%m-%d %H:%M"), readonly: "readonly" %>
      <% else %>
        <%= form.text_field :start_date , class: "date-picker flatpickr-input", placeholder: "Select date..", type: "text", readonly: "readonly" %>
      <% end %>
    </div>
    <div class="input-field date-pickers">
      <%= form.label :end_date, style: "display: block", class: "text-b " %>
      <% if task.end_date %>
        <%= form.text_field :end_date , class: "end-date flatpickr-input", placeholder: "Select date..", type: "text", value: task.end_date.strftime("%^b %-d, %Y %I:%M %p"), readonly: "readonly" %>
      <% else %>
        <%= form.text_field :end_date , class: "date-picker flatpickr-input", placeholder: "Select date..", type: "text", readonly: "readonly" %>
      <% end %>
    </div>
  </div>
  <%# edit Collab %>
  <% if request.path != new_task_path %>
    <div class="collaborators mb-3" style="max-width: 500px;">
      <h3 class="hd-md">Collaborators</h3>
      <div class="flex f-c">
        <% @collaborators.each do |collaborator| %>
          <div class="input_field flex f-center mb-2 pos-rel">
            <input type="email" name="collab[existing_emails][]" value="<%= collaborator.email%>" class="collab-email-input" id="collab[existing_emails]" placeholder="email" readonly>
            <span class="material-symbols-outlined rounded p-sm bg-err text-w ml-2 cursor-p text-md" id="mark-remove-email">
              person_remove
            </span>
            <div class="flex f-center ml-2 p-1 ">
              <p class="text-sm w-100 <%= collaborator.is_accepted ? "bg-s" : "bg-err" %> p-sm rounded text-w text-center"><%= collaborator.is_accepted ? "Task_Accepted" : "Not_Accepted" %></p>
              <p class="text-sm w-100 <%= collaborator.is_completed ? "bg-s" : "bg-err" %> p-sm rounded text-w text-center ml-1"><%= collaborator.is_completed ? "Task_completed" : "Not_Completed" %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%# collabs %>
  <div class="mb-4 max-w-400">
    <h2 class="hd-md mt-4"> <%= request.path != new_task_path ? "Add New " : "" %> Collaborate</h2>
    <div class="flex f-c">
      <div class="input_field flex f-center pos-rel">
        <input type="email" name="collab[emails][]" class="collab-email-input" id="collab[emails]" placeholder="email" autocomplete="off">
        <span class="material-symbols-outlined p-1 rounded-sm bg-p text-w ml-2 cursor-p" id="add-email-input">
          add
        </span>
      </div>
    </div>
  </div>
  <% if task.is_completed || !task.is_completed || task.is_completed == nil %>
    <div class="input-field mb-2">
      <h3 class="hd-md">Task Completion Status</h3>
      <label class="toggle" for="task_is_completed">
        <input  type="hidden" name="task[is_completed]" value="0" autocomplete="off">
        <input type="checkbox" name="task[is_completed]"   class="toggle__input" id="task_is_completed" <%= task.is_completed ? "checked" : nil %> />
        <span class="toggle-track">
          <span class="toggle-indicator">
            <!--  This check mark is optional  -->
            <span class="checkMark">
              <svg viewBox="0 0 24 24" id="ghq-svg-check" role="presentation" aria-hidden="true">
                <path d="M9.86 18a1 1 0 01-.73-.32l-4.86-5.17a1.001 1.001 0 011.46-1.37l4.12 4.39 8.41-9.2a1 1 0 111.48 1.34l-9.14 10a1 1 0 01-.73.33h-.01z"></path>
              </svg>
            </span>
          </span>
        </span>
      </label>
    </div>
  <% end %>
  <div class="">
    <%= form.submit :class => 'btn btn-md w-100 rounded' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%# utility functions %>
<%
def is_current(path)
    if request.path == path
      return true
    else
      return false
    end
  end
%>
<%# Task Card %>
<div class="card p-2 <%= task.is_completed ? " bg-s " : " bg-p "  %>  rounded-lg task-card" id="<%= dom_id task %>" >
  <%# Title and poup menu %>
  <div class="flex f-space-between">
    <div class="flex f-c f-start">
      <a class="hd-md text-w capitize text-bl text-hover-underline <%= task.is_completed ? " text-line-through " : " "%>" href="<%= show_task_path(task.id)%>"><%= task.title.size > 13 ? (task.title[0..10] + "...") : task.title %></a>
    </div>
    <div class="flex f-center-vh">
      <div>
        <span class="material-symbols-outlined cursor-p popup-toggler icon bg-w rounded-o " id="popup-toggler" style="font-weight: bolder; padding:3px;">more_vert</span>
        <%# pop up menu %>
        <div class="popup-menu display-none">
          <ul>
            <% is_starred_page =  is_current(starred_tasks_path) %>
            <li class="popup-link"> <%= link_to  is_starred_page ? "Remove" : "Star" , is_starred_page ? remove_starred_path(task) : add_to_starred_path(task), method: is_starred_page ? :delete : :post %></li>
            <% if task.user_id == current_user.id %>
              <li class="popup-link"><%= link_to "Edit", edit_task_path(task) %></li>
              <li class="popup-link"><%= button_to "Delete", task, method: :delete, data: {"confirm": :"Are you sure?"}, class: "btn-link"%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%# due date %>
  <div class="flex f-c mt-2 text-sm">
    <p class=" text-w"><%= task.is_completed ? "Task Completed" : "Due on" %></p>
    <p class="flex f-center text-w mt-1 capitize text-bl">
      <span class="material-symbols-outlined text-md text-w mr-1">
        calendar_today
      </span>
      <%# end date %>
      <%= task.end_date.strftime("%^b %d, %Y %I:%M %p")  %>
    </p>
  </div>
  <%#  %>
  <%# bottom section collaborators and button action %>
  <div class="flex f-space-between f-center mt-3 ">
    <% if collabs.size() > 0 %>
      <div class="flex f-c">
        <p class=" text-w-hint">collaborators</p>
        <div class="flex">
          <div class="avatar-group">
            <div class="hidden-avatars text-sm">
              <%= collabs.size() %>
            </div>
            <% collabs.each do |collab| %>
              <div class="avatar-stack">
                <% if collab.avatar_url != nil %>
                  <img src="<%= collab.avatar_url %>" class="" alt="">
                <% else %>
                  <%= image_tag "avatar.png", class: "" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <%#  %>
    <%#  %>
    <%#  %>
    <%# action to complete %>
    <% if task.user_id == current_user.id %>
      <%# for owner  %>
      <% if !task.is_completed %>
        <%= link_to "Mark Complete", mark_complete_path(task.id), method: :patch,data: {"confirm": :"Are you sure?"}, class: "btn btn-peace" %>
      <% else %>
        <%= link_to "Mark uncomplete", mark_uncomplete_path(task.id), method: :patch,data: {"confirm": :"Are you sure?"}, class: "btn btn-peace" %>
      <% end %>
      <%# for collab %>
    <% elsif !task.is_completed  %>
      <% collab_is_complete =  collabs.select { |collab|  collab.user_id == current_user.id  } %>
      <% if !(collab_is_complete[0].is_completed) %>
        <%= link_to "Mark Complete", collab_mark_complete_path(task.id), method: :patch,data: {"confirm": :"Are you sure?"}, class: "btn btn-peace" %>
      <% else %>
        <%= link_to "Mark uncomplete", collab_mark_incomplete_path(task.id), method: :put,data: {"confirm": :"Are you sure?"}, class: "btn btn-success" %>
        <%# <p class="text-sm p-sm bg-s text-w rounded">You completed the task</p> %>
      <% end %>
    <% else %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="flex">
  <div>
  <a href="<%= tasks_by_date_path(Date.parse("#{@task.start_date}").strftime("%Y-%m-%d")) %>">
    <span class="material-symbols-outlined mr-3 p-1 bg-c rounded-o">
      arrow_back
    </span>
  </a>
  </div>
  <div class="w-100">
    <h1>Editing task</h1>
    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/index.html.erb
<%
  def collab_data(task_id)
    collab_data = Collaborator.joins(:user).joins("left join avatars on avatars.id = users.avatar_id").select("collaborators.user_id, collaborators.is_completed, avatars.avatar_url").where(task_id: task_id)
    return collab_data
  end
%>
<div>
  <div class="flex f-center mb-3">
    <h1 class="hd-lg">Tasks</h1>
    <div class="flex f-center ml-2">
      <a href="/tasks/date/<%= @date ? Date.parse("#{@date}").prev_day : Date.parse(Time.now.strftime("%Y-%m-%d")).prev_day %>">
        <span class="material-symbols-outlined mr-3 p-1 bg-c rounded-o">
          chevron_left
        </span>
      </a>
      <h4 id="cur-date"> <%= @date ? Date.parse("#{@date}").strftime("%Y-%m-%d") : Time.now.strftime("%Y-%m-%d") %> </h4>
      <a href="/tasks/date/<%= @date ? Date.parse("#{@date}").next : Date.parse(Time.now.strftime("%Y-%m-%d")).next %>">
        <span class="material-symbols-outlined ml-3 p-1 bg-c rounded-o">
          chevron_right
        </span>
      </a>
    </div>
    <div class="action">
      <span class="material-symbols-outlined ml-3 p-1 bg-c rounded-o show-on-small cursor-p" id="sidebar-toggler">
        calendar_month
      </span>
    </div>
  </div>
  <div class="tasks grid">
    <% if @tasks.size() > 0 %>
      <% @tasks.each do |task| %>
        <% unless task.is_completed %>
          <%= render task, collabs: collab_data(task.id) , collab_task: false %>
        <% end %>
      <% end %>
    <% else %>
      <div class="flex f-center f-center-vh" style="height: 300px">
        <h2 class="text-md text-center text-b-hint">No Tasks on this day!</h2>
      </div>
    <% end %>
  </div>
  <% if @collab_tasks.size() > 0 %>
    <h1 class="hd-lg mt-3 mb-2">Collabs By Others</h1>
    <div class="tasks grid">
      <% @collab_tasks.each do |task| %>
        <%= render task, collabs: collab_data(task.id), collab_task: true%>
      <% end %>
    </div>
  <% end %>
  <h1 class="hd-lg mt-3 mb-2">Completed Tasks</h1>
  <div class="tasks grid">
    <% @tasks.each do |task| %>
      <% unless !task.is_completed %>
        <%= render task, collabs: collab_data(task.id), collab_task: false %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1 class="hd-lg">Create New task</h1>

<%= render "form", task: @task %>

app/views/tasks/requests.html.erb
<h3>Collab requests</h3>

app/views/tasks/show.html.erb
<div class="flex">
  <div>
    <a href="<%= tasks_by_date_path(Date.parse("#{@task.start_date}").strftime("%Y-%m-%d")) %>">
      <span class="material-symbols-outlined mr-3 p-1 bg-c rounded-o">
        arrow_back
      </span>
    </a>
  </div>
  <div class="w-100">
    <h1 class="capitize mb-3"><%= @task.title %></h1>
    <h3>Description</h3>
    <div class="flex f-c p-2 bg-c rounded-sm" style="min-width: 300px; max-width: 700px">
      <p class="text-md mt-2 flex" style="line-height: 1.5;"><%= @task.description %></p>
    </div>
    <br>
    <div class="flex f-center f-jc-sb">
      <div>
        <h5>Start Date</h5>
        <p class="text-md mt-2 p-1 rounded bg-c"><%= @task.start_date.strftime("%b %d, %Y %I:%M %p") %></p>
      </div>
      <div>
        <h5>End Date</h5>
        <p class="text-md mt-2 p-1 rounded bg-c"><%= @task.end_date.strftime("%b %d, %Y %I:%M %p") %></p>
      </div>
    </div>
    <br>
    <div class="collaborators">
      <h3 class="test-md mb-3">Collaborators</h3>
      <% @collaborators.each do |collab| %>
        <% unless !collab.is_accepted  %>
          <div class="flex f-center f-jc-sb mb-2">
            <div class="flex f-center-vh">
              <% if collab.avatar_url != nil %>
                <%= image_tag collab.avatar_url, class: "avatar avatar-sm" %>
              <% else %>
                <%= image_tag "avatar.png", class: "avatar avatar-sm" %>
              <% end %>
              <p class="text-md ml-2"><%= collab.email %></p>
            </div>
            <p class="text-sm ml-4 text-bl <%= collab.is_completed ? "text-success" : "text-error"%> "><%= collab.is_completed ? "Completed" : "Task Incomplete"%></p>
          </div>
        <% end %>
      <% end %>
      <br>
      <br>
      <h3 class="test-md mb-3">Collab Requests</h3>
      <% @collaborators.each do |collab| %>
        <% unless collab.is_accepted  %>
          <div class="flex f-center f-jc-sb mb-1">
            <div class="flex f-center">
              <% if collab.avatar_url != nil %>
                <%= image_tag collab.avatar_url, class: "avatar avatar-sm" %>
              <% else %>
                <%= image_tag "avatar.png", class: "avatar avatar-sm" %>
              <% end %>
              <p class="text-md ml-2"><%= collab.email %></p>
            </div>
            <p class="text-sm ml-4 text-bl text-error ">Pending</p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>