config/routes.rb
Rails.application.routes.draw do
  resources :avatars
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  resources :tasks
  resources :starred_tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  patch "/users/edit/avatar/:id", to: "application#change_avatar"
  get "/tasks/date/:date", to: "tasks#get_tasks_by_date", as: "tasks_by_date"
  patch "/tasks/:id/task_complete", to: "tasks#mark_complete",  as: "mark_complete"
  patch "/tasks/:id/task_uncomplete", to: "tasks#mark_uncomplete" , as: "mark_uncomplete"
  get "/tasks/:id", to: "tasks#show", as: "show_task"


  # collab
  get "/collab", to: "tasks#collab_requests", as: "collab_request"
  patch "/collab/accept/:task_id", to: "collaborators#accept_request", as: "accept_request"
  patch "/collab/reject/:task_id", to: "collaborators#reject_request", as: "reject_request"
  patch "/collab/complete/:task_id", to: "collaborators#mark_complete", as: "collab_mark_complete"
  put "/collab/complete/:task_id", to: "collaborators#mark_uncomplete", as: "collab_mark_incomplete"

  # collab email API
  get "/collab/emails/:email_string", to: "collaborators#get_emails"


  # starred tasks
  get "/starred_tasks/", to: "starred_tasks#index"
  post "/starred_tasks/:id", to: "starred_tasks#add", as:"add_to_starred"
  delete "/starred_tasks/:id", to: "starred_tasks#destroy", as:"remove_starred"

end

app/models/avatar.rb
class Avatar < ApplicationRecord
  has_one_attached :image
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :set_avatar, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!


  # GET /avatars or /avatars.json
  def index
    @avatars = Avatar.all
  end

  # GET /avatars/1 or /avatars/1.json
  def show
    avatar = Avatar.find(params[:id])
    render :json => {:image => url_for(avatar.image)}
  end

  # GET /avatat/

  # GET /avatars/new
  def new
    @avatar = Avatar.new
  end

  # GET /avatars/1/edit
  def edit
  end

  # POST /avatars or /avatars.json
  def create
    @avatar = Avatar.new(avatar_params)

    respond_to do |format|
      if @avatar.save
        @avatar.update({avatar_url: url_for(@avatar.image)})
        format.html { redirect_to "/users/edit", notice: "Avatar was successfully created." }
        format.json { render :show, status: :created, location: @avatar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avatars/1 or /avatars/1.json
  def update
    respond_to do |format|
      if @avatar.update(avatar_params)
        format.html { redirect_to avatar_url(@avatar), notice: "Avatar was successfully updated." }
        format.json { render :show, status: :ok, location: @avatar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avatars/1 or /avatars/1.json
  def destroy
    @avatar.destroy

    respond_to do |format|
      format.html { redirect_to avatars_url, notice: "Avatar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avatar
      @avatar = Avatar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def avatar_params
      params.require(:avatar).permit(:image)
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/views/avatars/_avatar.html.erb
<div id="<%= dom_id avatar %>">
<%= avatar.id %>
<%= image_tag avatar.image %>
</div>

app/views/avatars/_form.html.erb
<%= form_with(model: avatar) do |form| %>
  <% if avatar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(avatar.errors.count, "error") %> prohibited this avatar from being saved:</h2>

      <ul>
        <% avatar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form.file_field :image %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/avatars/edit.html.erb
<h1>Editing avatar</h1>

<%= render "form", avatar: @avatar %>

<br>

<div>
  <%= link_to "Show this avatar", @avatar %> |
  <%= link_to "Back to avatars", avatars_path %>
</div>

app/views/avatars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Avatars</h1>

<div id="avatars">
  <% @avatars.each do |avatar| %>
    <%= render avatar %>
    <p>
      <%= link_to "Show this avatar", avatar %>
    </p>
  <% end %>
</div>

<%= link_to "New avatar", new_avatar_path %>

app/views/avatars/new.html.erb
<h1>New avatar</h1>

<%= render "form", avatar: @avatar %>

<br>

<div>
  <%= link_to "Back to avatars", avatars_path %>
</div>

app/views/avatars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @avatar %>

<div>
  <%= link_to "Edit this avatar", edit_avatar_path(@avatar) %> |
  <%= link_to "Back to avatars", avatars_path %>

  <%= button_to "Destroy this avatar", @avatar, method: :delete %>
</div>